stevemk14ebr/PolyHook_2_0

headers/Misc.hpp
Just noticed this after you merged the PR.
Sorry about that.
Signed-off-by: Randshot <randshot@norealm.xyz>
=> Correct toupper -> towupper

CMakeLists.txt
ASMJIT should load if FEATURE_INLINENTD is set, the comments incorrectly labeled the ASMJIT loading as test code and so it didn't run if BUILD_DLL was set. This caused the build to fail when FEATURE_INLINENTD and BUILD_DLL were set. I simply removed this check as I believe it was accidently added when duplicating existing code.
=> Removed incorrect check for BUILD_DLL in loading of ASMJIT

headers/ErrorLog.hpp
Calling back() on an empty vector results in an assertion.
=> Fix crash on ErrorLog::pop()

headers/MemProtector.hpp
Fixed warning C4005 macro redefintion caused by MemProtector.hpp not checking if the macro is already defined.
=> Fixed warning C4005 macro redefinition

CMakeLists.txt, UnitTests/TestDetourNoTDx64.cpp, UnitTests/TestDetourNoTDx86.cpp, UnitTests/TestDetourx64.cpp, UnitTests/TestDetourx86.cpp, headers/Detour/ILCallback.hpp, headers/IHook.hpp, headers/Instruction.hpp, headers/MemProtector.hpp, headers/PageAllocator.hpp, sources/ADetour.cpp, sources/ILCallback.cpp, sources/MemProtector.cpp
These changes allow PolyHook 2 to be built successfully with the MinGW toolchain.
MSVC also builds PH2 successfully with the patches.
Below are tests results with MSVC and MinGW, targeting both 32 and 64 bit, on Release mode:
- MSVC
- 32: everything passed.
- 64: 1 test failed on `UnitTests/TestDetourNoTDx64.cpp` in line 114 with: `[!] Error: Cannot fixup IP relative data operation, relocation beyond displacement size`.
- MinGW:
- 32: 1 test failed on `UnitTests/TestDetourx86.cpp` in line 191.
- 64: 1 test failed on `UnitTests/TestDetourx64.cpp` in line 120 with: `[!] Error: Function too small to hook safely!`.
The tests were ran with MinGW version 9.2.0 and MSVC 2017 version 15.9.8, on a Windows 10 Pro version 1809 virtual machine.
=> Various fixes to allow compilation with MinGW

polyhook2/Exceptions/HWBreakPointHook.hpp, sources/HWBreakPointHook.cpp
Adds an overload of hook/unHook that takes a HANDLE as a parameter. 
This could be used to apply the hook to all active threads or a specific thread you aren't currently on.
=> Allow a thread handle to be passed to HWBreakPointHook's hook/unHook

CMakeLists.txt, UnitTests/TestDetourNoTDx64.cpp, UnitTests/TestDetourNoTDx86.cpp, UnitTests/TestDetourx64.cpp, UnitTests/TestDetourx86.cpp, UnitTests/TestVFuncSwapHook.cpp, UnitTests/TestVTableSwapHook.cpp, polyhook2/Detour/ADetour.hpp, polyhook2/Detour/x64Detour.hpp, polyhook2/Detour/x86Detour.hpp, polyhook2/ErrorLog.hpp, polyhook2/IHook.hpp, sources/EatHook.cpp, sources/IatHook.cpp, sources/ZydisDisassembler.cpp
This PR has fixes for warnings produced when building PH2 with Clang.
Almost all tests pass when building for 64 bits - sometimes the detour hooks fail with `Cannot fixup IP relative data operation, needed disp. beyond max disp range`.
All the tests pass with 32 bits builds.
Configuration used: Debug
Compilers and CMake generators used:
- MSVC 19.25.28610.4 with 'Visual Studio 16 2019' solution;
- Clang 9.0.0 with 'Visual Studio 16 2019' Solution;
- Clang 8.0.1 and 9.0.0 with Ninja
=> Clang compilation fixes

Catch.hpp
The text will generate a warning then as an error, under none western locale. 
"warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss..."
=> fixed a warning

CMakeLists.txt
fixes regression from e2e2c56a9bc23aa4c45ad3dfdb067b1a629962e2
It copies zycore headers to the installation prefix.
Without it you will get error that `Zycore/Defines.h` is not found.
=> cmake: fix Zycore missing headers on installation

CMakeLists.txt
This is based on the vcpkg patch for using the vcpkg built capstone when building polyhook2:
https://github.com/microsoft/vcpkg/blob/3f75ce5/ports/polyhook2/fix-build-error.patch
This patch should make it easier to also use zydis and asmjit builds of polyhook2 with vcpkg, and possibly other systems.
=> cmake: support use of external capstone, zydis, and asmjit libraries

.gitignore, CMakeLists.txt, UnitTests/TestVTableSwapHook2.cpp, polyhook2/Virtuals/VTableSwapHook.hpp, sources/VTableSwapHook.cpp
As I was migrating some code from the old polyhook to polyhook2, I found myself in need of using the new VTableSwapHook API since the VFuncDetour is no longer part of polyhook2. I found the interface somewhat non-intuitive to use, especially with all the type casts that are required to convert back and forth between integers and function pointers, and therefore I wrote a wrapper template class that is easier to use, with more straightforward boilerplate.
The template does type checking on the function signatures so you cannot accidentally hook a method with the wrong type signature. It also hooks in the constructor (throwing an exception on failure), and unhooks on destruction, following the RAII idiom (when a hook is used as a resource, which would be a common use case). Repeated …
=> VTableSwapHook2 template class for simpler API

MainTests.cpp, polyhook2/ErrorLog.hpp, sources/ADetour.cpp, sources/AVehHook.cpp, sources/CapstoneDisassembler.cpp, sources/EatHook.cpp, sources/ErrorLog.cpp, sources/HWBreakPointHook.cpp, sources/ILCallback.cpp, sources/IatHook.cpp, sources/ZydisDisassembler.cpp, sources/x64Detour.cpp, sources/x86Detour.cpp
To intercept the polyhook log, clients have to periodically call PLH::ErrorLog::singleton().pop() until the log queue is empty, which is somewhat inconvenient. This patch allows clients to register their own logging callback, ensuring that log messages can be captured by the client instantly, allowing different logging systems from the default, and also allowing the client to simply disable logging if so desired.
I've chosen not to register any logger by default, since I imagine most applications will want to implement their own logging callback. The default logger can be enabled with (also see MainTests.cpp):
```cpp
auto logger = std::make_shared<PLH::ErrorLog>();
PLH::Log::registerLogger(logger);
```
It might make sense to eventually deprecate PLH::ErrorLog from the main API and move it …
=> Allow clients to provide their own logging callback.

UnitTests/TestVTableSwapHook.cpp, sources/VFuncSwapHook.cpp, sources/VTableSwapHook.cpp
I ran into a rather subtle bug when attempting to hook a VTableSwapHook with an invalid virtual function index. For some reason, m_Hooked was set to true even if the hook failed. It turns out this can happen simply because m_Hooked is never initialised in this case. This patch fixes this by fully initialising all member variables of VTableSwapHook and VFuncSwapHook, and also adds a test case.
=> Variable initialisation fix.

UnitTests/TestVTableSwapHook.cpp, sources/VTableSwapHook.cpp
Unfortunately in my previous patch in #75, the newly added test fails under the debug build. It's entirely my fault for not testing the debug build separately. Attached is a possible fix but I have some design questions, and so maybe a different fix is needed depending what you want.
1. Is the logging as in the patch appropriate? If so, what is the precise convention for the different levels? I've assumed INFO is for purely informative messages, WARN is for warning messages that are not going to crash the application (any recoverable error, e.g. failing to hook), and SEV is for severe errors that are likely going to cause crashes. See for instance https://stackoverflow.com/a/2031209 for a classical interpretation. Is that correct?
2. The debug build test suite failure in question was …
=> Fix debug test failure.

polyhook2/Detour/x64Detour.hpp
std::placeholders is part of functional header
fixes #87
=> detour: fix compilation of x64detour

UnitTests/TestDisassembler.cpp, UnitTests/TestEatHook.cpp, polyhook2/PE/PEB.hpp, polyhook2/PageAllocator.hpp
The vc2019 cannot compile the code (UnitTests\TestDisassembler.cpp) with error C2440:
```
error C2440: 'initializing': cannot convert from 'initializer list' to 'std::vector<char *,std::allocator<char *>>'
note: No constructor could take the source type, or constructor overload resolution was ambiguous
```
=> - fix vc2019 compiler error for unit-tests;

polyhook2/Detour/ADetour.hpp, polyhook2/Detour/x64Detour.hpp, polyhook2/Detour/x86Detour.hpp, sources/ADetour.cpp, sources/x64Detour.cpp, sources/x86Detour.cpp
Currently Detour::followJmp() is hardcoded to max recursion depth of 5. In some use cases this limit is not sufficient (example: several hooks placed on the same function by multiple independent programs) and changes to it require recompiling the library.
This PR allows max recursion depth to be specified per x86Detour / x64Detour.
=> User-configurable max recursion depth in Detour::followJmp for x86Detour and x64Detour

UnitTests/windows/TestEatHook.cpp, polyhook2/PE/EatHook.hpp, polyhook2/PolyHookOs.hpp, sources/EatHook.cpp
This PR implements support for absolute module paths & module handles for EAT Hooks as discussed in #114.
Some miscellaneous optimizations suggested by Clang-tidy have also been applied.
New tests have been added that cover the new use cases, and test names have been rephrased to reflect that change.
=> Support for absolute paths & module handles in EAT hooks

polyhook2/Detour/x64Detour.hpp, polyhook2/Detour/x86Detour.hpp, polyhook2/Exceptions/BreakPointHook.hpp, polyhook2/Exceptions/HWBreakPointHook.hpp, polyhook2/PE/EatHook.hpp, polyhook2/PE/IatHook.hpp, polyhook2/Virtuals/VFuncSwapHook.hpp, polyhook2/Virtuals/VTableSwapHook.hpp
This PR changes the accessibility modifier of `IHook` descendants from `private` to `protected`. This leave the door open to useful inheritance for unforeseen use cases (if we could foresee them, we would implement public interfaces for that). It also partially facilities quick testing of new features/bug-fixes via inheritance, which can be easier than having to clone and setup the library from sources.
Other classes that have `private` members have not been modified in a similar fashion. But should they?
=> Increased IHook descendants' member accessibility

UnitTests/windows/TestDetourx64.cpp, UnitTests/windows/TestDisassembler.cpp, polyhook2/Instruction.hpp, sources/ADetour.cpp, sources/ZydisDisassembler.cpp, sources/x64Detour.cpp
This PR fixes displacement size calculation when instructions contain both IP-relative displacement and immediate values. I think this case warrants a new unit test that covers this scenario. Perhaps it can be added once the RIP-relative hooking feature is complete.
It also raises visibility of `m_displacement` member so that it is in line with member usages. However, I do believe that class members need to be revisited at some point because some public members (e.g. `m_isIndirect`) are public, but nevertheless have getters, which are used sometimes but not always, leading to inconsistencies. I believe a classical OOP encapsulation is warranted once main work has been done.
Finally, a new unit test is introduced that targets RIP-relative hooking. Naturally it fails for now, but it is …
=> Displacement size fix

CMakeLists.txt
This PR fixes a static vs shared issue when Detour feature is enabled. Right now there is a bug where asmjit will be included as a shared lib even if asmtk is configured as static lib. It's important that asmjit follows asmtk's linkage, otherwise it leads to a mess.
=> Fix asmjit lib when internal asmtk is used

.idea/codeStyles/Project.xml, CMakeLists.txt, UnitTests/windows/TestDetourSchemex64.cpp, UnitTests/windows/TestDetourTranslationx64.cpp, UnitTests/windows/TestDetourx64.cpp, UnitTests/windows/TestDetourx86.cpp, polyhook2/Detour/x64Detour.hpp, sources/ZydisDisassembler.cpp, sources/x64Detour.cpp, sources/x86Detour.cpp
This PR makes changes to the x64 detour scheme. The old INPLACE scheme is now INPLACE_SHORT, and uses rax register. The new INPLACE scheme now creates a non-spoiling trampoline, but at the expense of larger size. New `TestDetourSchemex64.cpp` unit tests are targeting those schemes (except Valloc2, which is tested in every other detour unit test anyway).
All tests pass except the last code-cave one. It always fails with
> No code caves found near function
Any ideas how we could ensure code cave allocation that will be found during a hook?
=> Safe in-place scheme

polyhook2/Detour/ADetour.hpp, sources/ADetour.cpp
This small PR brings in mostly QoL changes to the `make_nops` function that I hope you find useful.
Also, can we turn on the branch protection for the `master` branch to disable pushing directly to master? I feel uneasy pushing to master on my fork these days, for the fear of accidentally pushing to upstream instead, because sometimes I change remote url in my projects when testing new commits.
=> Optimized nop maker

polyhook2/PolyHookOs.hpp, sources/PolyHookOs.cpp
PolyHook2Alloca allocates memory dynamically on the stack but it wasn't being inline, causing the memory to be deallocated after it returned.
resolve #149 
Tested only on Windows MSVC.
=> Fixes PolyHook2Alloca not being inlined

polyhook2/IHook.hpp
Adds more interactions regarding a hook's hooked state, now allowing for retrieval of current state and state attribution through a boolean.
resolves #155
=> m_hooked interactions

CMakeLists.txt, polyhook2/Detour/NatDetour.hpp
Created because I found myself having to do this on every project of mine which used Polyhook2.
Adds a typedef to whichever detour works with the current compilation environment, be it x64Detour or x86Detour. The typedef is named NatDetour, it also includes the proper header.
=> Native Detour typedef

CMakeLists.txt, polyhook2/PolyHookOs.hpp, sources/ZydisDisassembler.cpp
Removes missplaced source path which breaks cmake build in CMakeLists.txt.
"__attribute__((always_inline))" needs an additional "inline" to build correctly.
gcc does not like the goto statement without the curly brackets. 
With these changes polyhook should build fine on linux.
=> cmake and linux specific bugfixes 

polyhook2/PolyHookOs.hpp
MinGW32 also requires the [defines we have for MinGW64](https://github.com/stevemk14ebr/PolyHook_2_0/blob/b78f13b20b88e217570ba5a0325b5bfe96f52404/polyhook2/PolyHookOs.hpp#L8C1-L17C1)
=> Add required defines for mingw32

sources/ZydisDisassembler.cpp
Fix to #180.
I was also having trouble hooking some WinAPI functions in my system. After some debugging, I found out **Detour::followJmp** was not following the jump because **Instruction::m_isIndirect** was not being correctly set to true, so **Instruction::getDestination()** failed. The jmp opcode is 0x25 and not 0x15, as shown by x64dbg's disassembler:
=> Fixed jmp opcode (0x25) which should not be the call opcode (0x15)

polyhook2/Instruction.hpp
When compiling my x86 hooking code, I was getting the following warning in MSVC:
`1>C:\vcpkg\installed\x86-windows\include\polyhook2\Instruction.hpp(198,3): warning C4018: '<=': signed/unsigned mismatch`
=> Fix compile warning in x86

sources/MemAccessor.cpp
Check #184 to see my comment on what this is attempting to fix.
=> Fix to failing to disassemble at the end of a memory region.

polyhook2/Instruction.hpp, sources/x64Detour.cpp, sources/x86Detour.cpp
* Print the `m_fnAddress` address at the beginning: If disassembling yields an empty instructions list, it will still log out the address
* Print the instructions directly after disassembling: If any error occurred shortly afterwards (e.g. in `followJmp`), we still get logging output of the instructions
=> Improve logging

sources/FBAllocator.cpp
The expression '(size)' is unused and generates a warning [-Wunused-value] in FBAllocator.cpp at line 77, column 6.
This line is very irritating, especially with -Werror, so it is better to delete it.
It did not appear to have much logic anyway.
=> Fixed warning in FBAllocator.cpp

CMakeLists.txt
POLYHOOK_BUILD_STATIC_RUNTIME changes how other libraries that PolyHook2 uses have their runtime linked, but it does not change this for asmjit properly.
=> Fix POLYHOOK_BUILD_STATIC_RUNTIME inconsistency

polyhook2/Instruction.hpp
This reduces the possibility of crashes when hooking without suspendthreads.
The best option may be to stop the entire execution, because even change the order there is a possibility that is hooking while executing at the target address, thus leading to uncontrollable results. But at least doing so does not expose the target to a jump to an uncontrolled address.
=> Prioritizes writing the jump target address before the actual hook

CMakeLists.txt
- use normal variable for non-options
- apply force param to cache entry
- separate zydis and zycore options
- disable doxygen by default
=> refine passing options to subdir

polyhook2/PE/IatHook.hpp, sources/IatHook.cpp
Also made moduleName a reference for good measure, and so clion wouldn't tell me that it's copied.
Apparently this has been unnoticed since 2018 https://github.com/stevemk14ebr/PolyHook_2_0/commit/810068a6b4a8664f590d353b796437255483dc68#diff-00cb1ee7bf12270d7c614126cfdc95d9071053c57453e39d1371a9dca10d4f66
=> Pass module name to FindIatThunk
